import {siteImages} from './brands.js';
import {company} from './data.js';
import {icon} from './icons.js';
import {tastarContent} from './tastar-content.js';

export function renderBusinessPage(business, base) {
  const image = siteImages.approach;
  return `<section id="home" class="business-hero wrap">
    <nav class="business-breadcrumb" aria-label="Breadcrumb"><a href="${base}">Home</a><span aria-hidden="true">/</span><span aria-current="page">${business.name}</span></nav>
    <div class="business-hero-grid"><div><div class="eyebrow">AGRICULTURAL CONSULTING SINCE 2013</div><img class="business-mark" src="${base}brand/tastar-cycle-mark-dark.svg" alt="" width="90" height="90"/><h1>TASTAR</h1><p class="business-full-name">${business.fullName}</p><p class="lead">${tastarContent.introduction}</p><a href="#contact" class="button button-forest" data-inquiry="General Inquiry" data-division="${business.name}">Connect with ${business.name} ${icon('northeast')}</a></div><img class="business-hero-photo" src="${base+image.src.slice(1)}" alt="${image.alt}" width="800" height="700" fetchpriority="high"/></div>
  </section>
  <section class="tastar-purpose section wrap" aria-labelledby="tastar-purpose-title"><div class="eyebrow">PEOPLE. COMMUNITIES. ENVIRONMENT.</div><h2 id="tastar-purpose-title">Our purpose and values.</h2><div class="tastar-purpose-grid"><article><h3>Our vision</h3><p>${tastarContent.vision}</p></article><article><h3>Our mission</h3><p>${tastarContent.mission}</p></article></div><div class="tastar-values">${tastarContent.values.map(([name,description],i)=>`<article><span class="micro">0${i+1}</span><div><h3>${name}</h3><p>${description}</p></div></article>`).join('')}</div></section>
  <section class="business-support section"><div class="wrap"><div class="section-top"><div><div class="eyebrow">TASTAR</div><h2>Key service areas.</h2></div><p>Our areas of work connect crop production, resource management, technology, and enterprise development. Contact us to discuss the scope and needs of your project.</p></div><div class="business-focus-grid">${tastarContent.services.map(service=>`<article>${icon(service.icon)}<h3>${service.name}</h3>${service.description ? `<p>${service.description}</p>` : ''}</article>`).join('')}</div><a class="underlined" href="${base}#products">Explore products and resources ${icon('northeast')}</a></div></section>
  <section class="business-connection section wrap"><div><div class="eyebrow">EXPERIENCE IN PRACTICE</div><h2>Speak with an agronomist.</h2><p>Speak with ${company.contact}, Agronomist / Plant Biologist, about your crops, technical needs, and market opportunities.</p><a class="underlined" href="${base}#profile">Meet Valerio ${icon('northeast')}</a></div><aside><span class="micro">RESEARCH. PRODUCTION. GROWER SUPPORT.</span><h3>Experience that informs advice.</h3><p>Explore Valerio&#39;s work in agricultural research, production management, food safety, and consulting.</p><a class="underlined" href="${base}#experience">View professional experience ${icon('northeast')}</a></aside></section>`;
}
